from django.conf.urls import url
from dashboard.views import *

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name="dashboard"),
    url(r'^account-settings/$', AccountSettingsView.as_view(), name='account-settings'),
    url(r'^subscription/$', SubscriptionView.as_view(), name='subscription'),
    # url(r'^biling/$', BilingView.as_view(), name='biling'),
    url(r'^invoices/$', InvoicesView.as_view(), name='invoices'),
    url(r'^invoices/show$', InvoiceDetailView.as_view(), name='invoice_detail'),
    url(r'^assets/$', AssetsView.as_view(), name='assets'),
    url(r'^assets/new$', AssetNewView.as_view(), name='asset_new'),
    url(r'^assets/show$', AssetShowView.as_view(), name='asset_show'),
    url(r'^software/$', SoftwareView.as_view(), name='software'),
    url(r'^software/new$', SoftwareNewView.as_view(), name='software_new'),
    url(r'^software/show$', SoftwareShowView.as_view(), name='software_show'),
    url(r'^users/$', UsersView.as_view(), name='users'),
    url(r'^users/new$', UsersNewView.as_view(), name='users_new'),
    url(r'^users/show$', UserShowView.as_view(), name='user_show'),
    # url(r'^reports/$', ReportsView.as_view(), name='reports'),
    url(r'^company/$', CompanyView.as_view(), name='company'),
    url(r'^company/new$', CompanyNewView.as_view(), name='company_new'),
    url(r'^hardware/$', HardwareView.as_view(), name='hardware'),
    url(r'^hardware/new$', HardwareNewView.as_view(), name='hardware_new'),
    url(r'^location/$', LocationView.as_view(), name='location'),
    url(r'^location/new$', LocationNewView.as_view(), name='location_new'),
    url(r'^manufacturers/$', ManufacturersView.as_view(), name='manufacturers'),
    url(r'^manufacturers/new$', ManufacturersNewView.as_view(), name='manufacturers_new'),
    url(r'^supplier/$', SupplierView.as_view(), name='supplier'),
    url(r'^supplier/new$', SupplierNewView.as_view(), name='supplier_new'),
]