# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20160818_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
