# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20160818_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(default='XXX000100001', editable=False, max_length=12, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('id', 'asset_tag')]),
        ),
    ]
