# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_asset_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([]),
        ),
    ]
