# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20160818_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_id',
        ),
    ]
